### ISSUE TITLE
Borders

### ISSUE THREAD

**Issue by cagnulein** [dimagoltsman/refreshable-picture-card#1]
Hi, your card works fine! But i have a strange borders issue as you can see here. Can i fix them in some way?
Thanks
![Immagine](https://user-images.githubusercontent.com/48216/82425037-4872ce00-9a86-11ea-85e6-67ef4e4e2b61.png)

**Comment by dimagoltsman** [comment]
does it work ok if you add `title` to the config?

**Comment by cagnulein** [comment]
> does it work ok if you add `title` to the config?

yes it does

**Comment by dimagoltsman** [comment]
fixed.
can you update to 0.1.2 and tell me if its ok now? (without title)

**Comment by cagnulein** [comment]
Thanks man!
