### ISSUE TITLE
Feature Request - Full Card Picture

### ISSUE THREAD

**Issue by Furegato** [dimagoltsman/refreshable-picture-card#16]
Hi,
If possible, I would like to request an extra visual option to have the picture fill the whole card, like the picture card.
Cheers!
![image](https://user-images.githubusercontent.com/38523813/172343456-76ab297c-31bb-44f0-8f59-e788d09ae6e1.png)

**Comment by dimagoltsman** [comment]
well, PRs are highly welcome :)

**Comment by jrlambs** [comment]
I haven't had a chance to dive in to create a PR yet, but it looks like the normal "picture" card that does not have borders uses this for css styles.  presumably conditionally adding these styles to the css variable in the plugin would do the trick: 
`
      ha-card {
        overflow: hidden;
        height: 100%;
      }
      ha-card.clickable {
        cursor: pointer;
      }
      img {
        display: block;
        width: 100%;
      }
   
`

https://github.com/home-assistant/frontend/blob/dev/src/panels/lovelace/cards/hui-picture-card.ts

**Comment by jrlambs** [comment]
PR is here: https://github.com/dimagoltsman/refreshable-picture-card/pull/17

**Comment by Furegato** [comment]
That worked great @jrlambs!
I have minimal coding experience, especially in this language. I had it almost working on my branch. It was 100% in width but there were still some leftovers on the height of it, but your solution absolutely nailed it!
Also, thanks for the path for the official HA picture card on Github, I tried to find it myself, but since I'm not very familiar with the project I could not find it. That is an amazing source of information!
Thank you!
