### ISSUE TITLE
entity_picture: camera.mjpeg_camera

### ISSUE THREAD

**Issue by cagnulein** [dimagoltsman/refreshable-picture-card#3]
Mjepg_camera entities don't work :(

`type: 'custom:refreshable-picture-card'
title: Garage
update_interval: 1
entity_picture: camera.mjpeg_camera_3
attribute: entity_picture`

**Comment by dimagoltsman** [comment]
can u give an example? what is the value of entity_picture in camera.mjpeg_camera_3  ?

**Comment by cagnulein** [comment]
> can u give an example? what is the value of entity_picture in camera.mjpeg_camera_3 ?

<pre>
camera:
  - platform: mjpeg
    mjpeg_url: "http://192.168.0.226:81/videostream.cgi?loginuse=admin&loginpas=xxxx"
    verify_ssl: false
    
</pre>

**Comment by dimagoltsman** [comment]
what is the value of entity_picture when you look at the entity in developer tools > states

**Comment by cagnulein** [comment]
<pre>
access_token: xxxxxxxxxxxxxxxxxxxxxxxx
friendly_name: Mjpeg Camera
entity_picture: >-
  /api/camera_proxy/camera.mjpeg_camera_3?token=xxxxxxxxx
supported_features: 0
</pre>

**Comment by dimagoltsman** [comment]
and when you put it in the browser, does it work?

http://yourhomeassistant:8123/api/camera_proxy/camera.mjpeg_camera_3?token=xxxxxxxxx

**Comment by cagnulein** [comment]
> and when you put it in the browser, does it work?
> 
> http://yourhomeassistant:8123/api/camera_proxy/camera.mjpeg_camera_3?token=xxxxxxxxx

Yes

**Comment by dimagoltsman** [comment]
and is it a picture, or a video stream?

**Comment by cagnulein** [comment]
it's a picture, if i refresh it a new snapshot will shown

**Comment by dimagoltsman** [comment]
got it.
i tested this snapshots with a few cameras and it works.
are you connected to the same network where HA runs?

**Comment by cagnulein** [comment]
Yes, same network

**Comment by dimagoltsman** [comment]
can you tell me from browser dev tools, what is the response type of this url?

**Comment by dimagoltsman** [comment]
another option is to put the full url in `static_picture` property

**Comment by cagnulein** [comment]
<pre>
HTTP/1.1 200 OK
Content-Type: image/jpeg
Content-Length: 40415
Date: Thu, 21 May 2020 07:11:26 GMT
Server: Python/3.7 aiohttp/3.6.1
</pre>

**Comment by dimagoltsman** [comment]
try putting it in static_picture

**Comment by cagnulein** [comment]
> try putting it in static_picture

but the token will change in the future...

**Comment by dimagoltsman** [comment]
just for testing

**Comment by cagnulein** [comment]
> just for testing

tried, it doesn't work. Same as with entity :(

**Comment by cagnulein** [comment]
<pre>
type: 'custom:refreshable-picture-card'
title: Reolink Camera
update_interval: 1
static_picture: >-
  http://192.168.0.83:8123/api/camera_proxy/camera.mjpeg_camera_3?token=xxxxx
</pre>

**Comment by dimagoltsman** [comment]
ok i think i found the bug, try updating now to 0.1.1 and tell me if it works

**Comment by cagnulein** [comment]
Yes it works!
Cheers!

**Comment by dimagoltsman** [comment]
thank you for the feedback and help fixing :)

**Comment by cagnulein** [comment]
sorry, i have to reopen. It works with a camera, but not with another :(
