### ISSUE TITLE
After about 5 minutes all the picture goes offline

### ISSUE THREAD

**Issue by cagnulein** [dimagoltsman/refreshable-picture-card#4]
I have 3 picture card with 1 second. All 3 cards, on the same time, go offline every about 5 minutes. If i refresh the browser or simply resize the browser window, all the pictures turn back online

**Comment by dimagoltsman** [comment]
hmm....
can you open the console and tell me if it stops printing the picture url also?

**Comment by cagnulein** [comment]
no the console output of your cards continue to print out

**Comment by dimagoltsman** [comment]
interesting....  so everything works but the picture just wont update?

**Comment by cagnulein** [comment]
yes, exactly

**Comment by cagnulein** [comment]
any ideas?

**Comment by dimagoltsman** [comment]
not yet, but ill take a look

**Comment by dimagoltsman** [comment]
well, i just kept it open for 30 minutes and everything works... it keeps updating

**Comment by cagnulein** [comment]
i'm using chrome, which browser did you test with?

**Comment by dimagoltsman** [comment]
same. with OSX macbook pro 18

**Comment by cagnulein** [comment]
could i help you in some way in order to solve this issue? I have the same thing on android with the HASSIO app

**Comment by dimagoltsman** [comment]
hard to say, i cant recreate it on my side....

**Comment by cagnulein** [comment]
it gives me this error in the console when it starts to display nothing

<pre>camera.mjpeg_camera_4:1 GET http://192.168.0.83:8123/api/camera_proxy/camera.mjpeg_camera_4?token=3a41e3c899d712f55aed230c41a18f24c958b996e9daad187e5b54b0cce00670&currentTimeCache=1593692763546 401 (Unauthorized)</pre>

maybe you have to recreate a token?

**Comment by cagnulein** [comment]
other info: with custom:surveillance-card everything works fine

**Comment by cagnulein** [comment]
https://github.com/home-assistant/core/issues/23055

**Comment by dimagoltsman** [comment]
yeah but its different....   and i cant recreate it thats a problem...

**Comment by dimagoltsman** [comment]
checked again.. not reproducing
