### ISSUE TITLE
Tap actions

### ISSUE THREAD

**Issue by jacquesvzijp** [dimagoltsman/refreshable-picture-card#5]
Great card, solved my problem for refreshing camera still images, excellent!
Feature request would be to support tap actions so you can e.g jump to the live stream for the camera in my case.

**Comment by dimagoltsman** [comment]
on it :)

**Comment by dimagoltsman** [comment]
done, you can update

**Comment by jacquesvzijp** [comment]
Thanks it does work and thanks for super fast response;-)

One question, however, as I am using the iOS app, it jumps out of the app to a browser session for home assistant. I'like to stay on the app;-) 

Thanks for considering it!

**Comment by dimagoltsman** [comment]
It only jumps on url, thats how HA work i guess...

**Comment by jacquesvzijp** [comment]
Btw I am using following:

navigate: /lovelace/camparking

**Comment by jacquesvzijp** [comment]
On standard HA cards (like e.g. picture-entity card) you can use:

tap_action:
  action: navigate
    navigation_path: /Lovelace/myview 

![image](https://user-images.githubusercontent.com/31371857/96753615-6b583400-13d0-11eb-930e-09e926411c6b.jpeg)

This works within the iOS app;-)

**Comment by dimagoltsman** [comment]
awesome! thats why i like doing it generic :)

**Comment by jacquesvzijp** [comment]
Okay you mean this should also work with your card? Because I tried and I did not get that to work... I will try again !

**Comment by jacquesvzijp** [comment]
I mean below does not work unfortunately:
![image](https://user-images.githubusercontent.com/31371857/96755725-5d57e280-13d3-11eb-8768-c26139447f5e.jpeg)

**Comment by dimagoltsman** [comment]
You have to use 'call' and 'data'
Other attributes wont work

**Comment by jacquesvzijp** [comment]
Thanks, I can't find any service call that will navigate to my desired view. Do you have any idea how to do that? It should be possible as the all others cards have this feature. I saw in your code you use window. which indeed starts a browser session. I am sure there must be some kind of Hass. API or service call that can change the view...

**Comment by jacquesvzijp** [comment]
Hi Dima,
Just to let you know, I found the solution. Using browser_mod integration, I use following:

type: 'custom:refreshable-picture-card'
static_picture: /local/snapahot.jpg
update_interval: 10
tap_action:
  call: browser_mod.navigate
  data:
    navigation_path: /lovelace/cam_stream
    deviceID: this

Now it nicely stays within the iOS app.
Thanks

**Comment by dimagoltsman** [comment]
nice!!!
