### ISSUE TITLE
tap-action full screen

### ISSUE THREAD

**Issue by vbetoglou** [dimagoltsman/refreshable-picture-card#7]
Is there a way to get the same behavior with some of the other cards, where tapping on the image enlarges it?

I tried doing this, but it didn't work very well:

```
type: 'custom:refreshable-picture-card'
title: null
update_interval: 300
entity_picture: 'http://127.0.0.1:8123/local/cron/TIMELINE1.jpg'
attribute: entity_picture
tap_action:
  action: more-info
```
I have an image I update via cron and I'd like for it to periodically refresh to see if there's a new version.  On-tap I'd like for it to enlarge.

**Comment by dimagoltsman** [comment]
not implemented, PRs are welcome
