### ISSUE TITLE
Cleaning browser cache

### ISSUE THREAD

**Issue by jurgenhaas** [dimagoltsman/refreshable-picture-card#8]
I'm a very happy user of this card and I'm using it to get updated images of by Unifi protect cameras around our proerty once a minute. I'm having HA open all day and night in a browser and discovered recently, that the PC and the browser started to behave strangely. It turned out that the browser cache grew to a size of more than 100GB and further investigation brought to light, that the updated images are kept in the browser cache and you can imagine how quickly that adds up to huge but meaningless data.

I wonder if there is a way to either clean the cache for this specifically by the javascript code or to not cache that data in the first place.

**Comment by dimagoltsman** [comment]
well i cant really control browser cache...  
i have 2 suggestions: 
1. increase the refresh time if thats ok
2. add a browser extention that clears site cach or reloads the page
